FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production
ENV REDIS_URL=redis://redis-stack:6379
ENV PORT=3000
ENV PGHOST=postgres
ENV PGPORT=5432
ENV PGDATABASE=afc
ENV PGUSER=postgres
ENV PGPASSWORD=""

ENV GOOGLE_CLIENT_ID=""
ENV GOOGLE_OAUTH_REDIRECT_URI=""
ENV GOOGLE_ALLOWED_EMAIL_DOMAIN=""
ENV PUBLIC_URL=""
ENV GOOGLE_CALLBACK_URL=""
ENV GOOGLE_OAUTH_STATE_TTL_SECONDS="300"
ENV GOOGLE_OAUTH_STATE_COOKIE_NAME="afc_google_oauth_state"
ENV HEALTHCHECK_TIMEOUT_MS="5000"
ENV BULK_STUDENT_IMPORT_MAX_FILE_BYTES="2097152"
ENV BULK_STUDENT_IMPORT_MAX_ROWS="1000"
ENV BULK_STUDENT_IMPORT_PREVIEW_TTL_SECONDS="600"
ENV TRUST_PROXY=""
ENV CORS_ALLOW_ANY_ORIGIN="false"
ENV CORS_ORIGIN=""
ENV GATEWAY_HOST="0.0.0.0"
ENV GATEWAY_PORT="3010"
ENV AFC_FRONT_TARGET="http://afc-front:3000"
ENV AFC_BACK_TARGET="http://afc-back:3000"

EXPOSE 3000 3010

CMD ["npm", "start"]