FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production
ENV REDIS_URL=redis://redis-stack:6379
ENV PORT=3000
ENV PGHOST=postgres
ENV PGPORT=5432
ENV PGDATABASE=afc
ENV PGUSER=postgres
ENV PGPASSWORD=admin

ENV GOOGLE_CLIENT_ID=""
ENV GOOGLE_CLIENT_SECRET=""
ENV GOOGLE_OAUTH_REDIRECT_URI=""
ENV GOOGLE_ALLOWED_EMAIL_DOMAIN=""
ENV GOOGLE_OAUTH_BRIDGE_START_URL=""
ENV GOOGLE_OAUTH_BRIDGE_VERIFY_URL=""
ENV GOOGLE_OAUTH_BRIDGE_SHARED_SECRET=""
ENV GOOGLE_OAUTH_BRIDGE_TIMEOUT_MS="5000"
ENV GOOGLE_OAUTH_BRIDGE_ATTEMPT_TTL_SECONDS="300"
ENV GOOGLE_OAUTH_BRIDGE_ATTEMPT_COOKIE_NAME="afc_oauth_attempt"

EXPOSE 3000

CMD ["npm", "start"]